"""
docs/source/conf.py - Sphinx configuration file
Chức năng: Cấu hình Sphinx để build documentation
Định nghĩa theme, extensions, paths, và metadata
"""

import os
import sys
from datetime import datetime

# -- Path setup --------------------------------------------------------------
# Thêm đường dẫn đến source code để Sphinx có thể import modules
sys.path.insert(0, os.path.abspath('../../src'))
sys.path.insert(0, os.path.abspath('../..'))

# -- Project information -----------------------------------------------------
project = 'Python Auto Grader PBT'
copyright = f'{datetime.now().year}, Pham Minh Ngoc Ha - Academy of Finance'
author = 'Pham Minh Ngoc Ha'

# Version info
# The short X.Y version
version = '1.0'
# The full version, including alpha/beta/rc tags
release = '1.0.0'

# -- General configuration ---------------------------------------------------
# Extensions để sử dụng
extensions = [
    'sphinx.ext.autodoc',        # Tự động tạo docs từ docstrings
    'sphinx.ext.napoleon',       # Support Google/NumPy style docstrings
    'sphinx.ext.viewcode',       # Thêm links đến source code
    'sphinx.ext.intersphinx',    # Link đến docs của projects khác
    'sphinx.ext.todo',           # Support TODO items
    'sphinx.ext.coverage',       # Coverage checker
    'sphinx.ext.mathjax',        # Render toán học
    'sphinx.ext.ifconfig',       # Conditional content
    'sphinx.ext.githubpages',    # GitHub Pages support
]

# Autodoc settings
autodoc_default_options = {
    'members': True,              # Document all members
    'member-order': 'bysource',   # Sắp xếp theo thứ tự trong code
    'special-members': '__init__', # Include __init__
    'undoc-members': True,        # Include members không có docstring
    'exclude-members': '__weakref__'
}

# Napoleon settings (Google style docstrings)
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The suffix(es) of source filenames.
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx.
language = 'en'

# -- Options for HTML output -------------------------------------------------
# Theme để sử dụng
html_theme = 'sphinx_rtd_theme'

# Theme options
html_theme_options = {
    'canonical_url': '',
    'analytics_id': '',
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'style_nav_header_background': '#2980B9',
    # Toc options
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

# Add any paths that contain custom static files
html_static_path = ['_static']

# Custom CSS
html_css_files = [
    'custom.css',
]

# Logo và favicon
# html_logo = '_static/logo.png'
# html_favicon = '_static/favicon.ico'

# HTML output options
html_title = f'{project} v{version}'
html_short_title = project
html_show_sourcelink = True
html_show_sphinx = True
html_show_copyright = True

# -- Options for LaTeX output ------------------------------------------------
latex_elements = {
    'papersize': 'a4paper',
    'pointsize': '10pt',
    'preamble': '',
    'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files.
latex_documents = [
    (master_doc, 'PythonAutoGraderPBT.tex',
     'Python Auto Grader PBT Documentation',
     'Pham Minh Ngoc Ha', 'manual'),
]

# -- Options for manual page output ------------------------------------------
man_pages = [
    (master_doc, 'pythonautograderpbt',
     'Python Auto Grader PBT Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------
texinfo_documents = [
    (master_doc, 'PythonAutoGraderPBT',
     'Python Auto Grader PBT Documentation',
     author, 'PythonAutoGraderPBT',
     'Automated grading system for Python assignments.',
     'Miscellaneous'),
]

# -- Extension configuration -------------------------------------------------

# Intersphinx mapping (link đến docs của projects khác)
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'hypothesis': ('https://hypothesis.readthedocs.io/en/latest/', None),
    'pytest': ('https://docs.pytest.org/en/stable/', None),
}

# TODO extension
todo_include_todos = True

# Coverage extension
coverage_show_missing_items = True
